module.exports.header1 = [
  "","","","","Quantity Per Day","","","","","",
  "","","","","","","","","","",
  "","","","","","","","","","",
  "","","","","","","","","","",
  "","","","","","","","","","",
  "","",""
]

module.exports.header2 = [
    "Store Code",
    "Store Name",
    "Product Name",
    "Barcode",
    "UoM",
    "1-Oct",
    "2-Oct",
    "3-Oct",
    "4-Oct",
    "5-Oct",
    "6-Oct",
    "7-Oct",
    "8-Oct",
    "9-Oct",
    "10-Oct",
    "11-Oct",
    "12-Oct",
    "13-Oct",
    "14-Oct",
    "15-Oct",
    "16-Oct",
    "17-Oct",
    "18-Oct",
    "19-Oct",
    "20-Oct",
    "22-Oct",
    "22-Oct",
    "23-Oct",
    "24-Oct",
    "25-Oct",
    "26-Oct",
    "27-Oct",
    "28-Oct",
    "29-Oct",
    "30-Oct",
    "31-Oct",
    "1-Nov",
    "2-Nov",
    "3-Nov",
    "4-Nov",
    "5-Nov",
    "6-Nov",
    "7-Nov",
    "8-Nov",
    "9-Nov",
    "10-Nov",
    "11-Nov",
    "12-Nov",
    "13-Nov",
    "14-Nov",
    "15-Nov",
    "16-Nov",
    "17-Nov"
  ];